### ISSUE TITLE
Stella Implementation

### ISSUE THREAD

**Issue by xw2d1** [ConnorChickenway/stella#1]
Hello!

I would like to use Stella in a project of mine, is there a release of Stella? Like Jitpack so I can implement it in my project using gradle? 

Cheers

**Comment by ConnorChickenway** [comment]
Hi, I've published a jitpack version. 

Link: https://jitpack.io/#ConnorChickenway/stella/v0.1

If you have a problem, let me know.

**Comment by xw2d1** [comment]
Hey, thanks for the release, but I'm afraid it still doesn't work.
As you'll see if you check the jitpack build.log for the "v0.1" release, it can't find "org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT". It looks like the core doesn't have the required papermc repository if u open the build.gradle of your "core"
It'd be great if you could fix this and make a new release!

Also, does Stella work with 1.20+? That would be really useful.
If not would you be able to make it work for 1.20? 

Build-Log **https://jitpack.io/com/github/ConnorChickenway/stella/v0.1/build.log**

Cheers

**Comment by xw2d1** [comment]
> Hi, I've published a jitpack version.
> 
> Link: https://jitpack.io/#ConnorChickenway/stella/v0.1
> 
> If you have a problem, let me know.

I'm really sorry to say that I'm still having trouble with the 0.3 release. 
You can always see this in the build log when you create a release, e.g. here: https://jitpack.io/com/github/ConnorChickenway/stella/v0.3/build.log.

There are again some errors, which is why the release does not work and I cannot integrate Stella into my project.


I would be really grateful if you could fix the errors.

Thank you!

**Comment by ConnorChickenway** [comment]
Hi, I’ve fixed it. You should now be able to use the API in your project.

https://jitpack.io/com/github/ConnorChickenway/stella/v0.4/build.log
